"""
extractor_excel_csv.py — Direct reading of Excel and CSV bank statement files.

Excel (.xlsx, .xls) and CSV (.csv) files are already structured in rows and columns,
so we do not need OCR or LLM processing to read them. Pandas — a Python data
analysis library — can read these files directly into a DataFrame (a table).

However, the column names in these files vary from bank to bank:
  - SBI may call a column "Withdrawal Amt" while HDFC calls it "Debit"
  - Some banks have separate "Value Date" and "Transaction Date" columns
  - The narration column might be called "Description", "Particulars", or "Remarks"

This module reads the raw file and attaches the Account_ID and Bank_Name
provided by the investigator. The standardiser (standardiser.py) then uses
the Groq column mapping to rename columns to the unified schema.

For Excel files, use openpyxl engine.
For CSV files, try multiple text encodings — Indian bank systems sometimes
produce CSV files with Windows-specific encoding that is not plain UTF-8.

Team: Survey Corps | CIDECODE Hackathon 2026 | CID Karnataka
"""

import logging
from pathlib import Path
from typing import Optional

import pandas as pd

# Set up a logger for this module.
logger = logging.getLogger(__name__)


def extract_dataframe_from_excel_csv(
    file_path: str,
    account_id: str,
    bank_name: str,
) -> pd.DataFrame:
    """
    Reads an Excel or CSV bank statement directly into a pandas DataFrame.

    Excel and CSV files already contain structured tabular data, so no
    OCR or LLM processing is needed. The data is read directly and
    immediately passed to the standardiser.

    Handles both .xlsx/.xls (via openpyxl) and .csv (via pandas read_csv).
    Tries multiple encodings for CSV files: utf-8, latin-1, cp1252.
    The cp1252 encoding is common in files generated by older Windows-based
    Indian banking software.

    Attaches Account_ID and Bank_Name to every row so the unified DataFrame
    always knows which account each transaction belongs to.

    Parameters:
        file_path (str): Absolute path to the Excel or CSV file.
        account_id (str): Investigator-provided account identifier
                          (e.g., "ACC001" or "SBI_RAVI_KUMAR").
        bank_name (str): Investigator-provided bank name (e.g., "SBI", "HDFC").

    Returns:
        pd.DataFrame: Raw DataFrame with original column names plus
                      Account_ID and Bank_Name columns added.
                      Returns empty DataFrame if the file cannot be read.
    """
    path = Path(file_path)
    extension = path.suffix.lower()

    logger.info(
        "extractor_excel_csv.extract_dataframe_from_excel_csv: "
        "Reading file '%s' for account '%s' at bank '%s'",
        path.name,
        account_id,
        bank_name,
    )

    df: Optional[pd.DataFrame] = None

    # ── Excel files (.xlsx or .xls) ───────────────────────────────────────────
    if extension in (".xlsx", ".xls"):
        df = _read_excel_file(file_path)

    # ── CSV files (.csv) ──────────────────────────────────────────────────────
    elif extension == ".csv":
        df = _read_csv_file(file_path)

    else:
        logger.error(
            "extractor_excel_csv.extract_dataframe_from_excel_csv: "
            "Unexpected extension '%s' — this extractor only handles Excel and CSV.",
            extension,
        )
        return pd.DataFrame()

    # If reading failed, return an empty DataFrame so the pipeline can continue.
    if df is None or df.empty:
        logger.warning(
            "extractor_excel_csv.extract_dataframe_from_excel_csv: "
            "File '%s' produced an empty DataFrame.",
            path.name,
        )
        return pd.DataFrame()

    # Attach the investigator-provided identifiers to every row.
    # This is essential for cross-account analysis — every transaction must
    # carry its account identity so we can trace money flows between accounts.
    df["Account_ID"] = account_id
    df["Bank_Name"] = bank_name

    logger.info(
        "extractor_excel_csv.extract_dataframe_from_excel_csv: "
        "Successfully read %d rows and %d columns from '%s'",
        len(df),
        len(df.columns),
        path.name,
    )

    return df


def _read_excel_file(file_path: str) -> Optional[pd.DataFrame]:
    """
    Reads an Excel file (.xlsx or .xls) using the openpyxl engine.

    Tries to skip header rows that are not column names (e.g., bank letterhead
    text that appears above the actual transaction table). If a standard read
    fails to find numeric data, it tries reading with header=None so that
    the standardiser can handle raw data.

    Parameters:
        file_path (str): Absolute path to the Excel file.

    Returns:
        pd.DataFrame or None: DataFrame if successful, None if reading fails.
    """
    try:
        # Read the Excel file. openpyxl is used for .xlsx files.
        # For .xls (older Excel format), pandas automatically uses xlrd if available,
        # or falls back to openpyxl for recent versions.
        df = pd.read_excel(file_path, engine="openpyxl")

        logger.info(
            "extractor_excel_csv._read_excel_file: "
            "Read Excel file with %d rows. Columns: %s",
            len(df),
            df.columns.tolist(),
        )
        return df

    except Exception as error:
        logger.error(
            "extractor_excel_csv._read_excel_file: "
            "Failed to read Excel file '%s': %s",
            file_path,
            error,
        )
        return None


def _read_csv_file(file_path: str) -> Optional[pd.DataFrame]:
    """
    Reads a CSV file, trying multiple text encodings until one succeeds.

    Indian bank software sometimes produces CSV files with Windows-specific
    character encodings (cp1252 or latin-1) rather than the standard UTF-8.
    This function tries UTF-8 first, then falls back to other encodings.

    Parameters:
        file_path (str): Absolute path to the CSV file.

    Returns:
        pd.DataFrame or None: DataFrame if successful, None if all encodings fail.
    """
    # List of encodings to try, in order of preference.
    # utf-8 is the modern standard.
    # latin-1 and cp1252 are common in older Windows banking systems.
    encodings_to_try = ["utf-8", "latin-1", "cp1252"]

    for encoding in encodings_to_try:
        try:
            df = pd.read_csv(file_path, encoding=encoding)
            logger.info(
                "extractor_excel_csv._read_csv_file: "
                "Successfully read CSV with encoding '%s'. %d rows, columns: %s",
                encoding,
                len(df),
                df.columns.tolist(),
            )
            return df

        except UnicodeDecodeError:
            # This encoding did not work — try the next one in the list.
            logger.debug(
                "extractor_excel_csv._read_csv_file: "
                "Encoding '%s' failed for '%s', trying next encoding.",
                encoding,
                file_path,
            )
            continue

        except Exception as error:
            logger.error(
                "extractor_excel_csv._read_csv_file: "
                "Unexpected error reading CSV '%s' with encoding '%s': %s",
                file_path,
                encoding,
                error,
            )
            return None

    # If all encodings failed, log a clear error message.
    logger.error(
        "extractor_excel_csv._read_csv_file: "
        "All encoding attempts failed for CSV file '%s'. "
        "Tried: %s",
        file_path,
        encodings_to_try,
    )
    return None
